// Merges data/tasks_base.json + data/prices.json + data/model_pricing.json
// + data/reliability_evidence.json into site/data.js (a window.AEVF_DATA payload).
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = f => JSON.parse(readFileSync(join(root, 'data', f), 'utf8'));

const base = read('tasks_base.json');
const prices = { tasks: readdirSync(join(root, 'data', 'partials'))
  .filter(f => f.endsWith('.json'))
  .flatMap(f => read(join('partials', f)).tasks) };
const pricing = read('model_pricing.json');
let evidence = { evidence: [], priors_note: '' };
try { evidence = read('reliability_evidence.json'); } catch { /* optional */ }

const priceById = Object.fromEntries(prices.tasks.map(t => [t.task_id, t]));

const tasks = base.tasks.map(t => {
  const p = priceById[t.task_id];
  if (!p) throw new Error(`missing price for ${t.task_id}`);
  return {
    ...t,
    price_low: p.price_low,
    price_base: p.price_base,
    price_high: p.price_high,
    human_minutes: p.human_minutes ?? null,
    price_basis: p.price_basis ?? '',
    price_status: p.status ?? 'estimated',
    sources: p.sources ?? [],
    price_notes: p.notes ?? ''
  };
});

const payload = {
  built: new Date().toISOString().slice(0, 10),
  retrieved: pricing.retrieved,
  models: pricing.models,
  historical: pricing.historical,
  pricing_note: pricing.status_note,
  evidence: evidence.evidence ?? [],
  evidence_note: evidence.priors_note ?? '',
  tasks
};

writeFileSync(join(root, 'site', 'data.js'),
  '// Generated by scripts/build_data.mjs. Do not edit by hand.\n' +
  'window.AEVF_DATA = ' + JSON.stringify(payload, null, 1) + ';\n');

console.log(`built site/data.js: ${tasks.length} tasks, ${pricing.models.length} models, ${payload.evidence.length} evidence rows`);
