// Merges data/tasks_base.json + data/prices.json + data/model_pricing.json
// + data/reliability_evidence.json into site/data.js (a window.AEVF_DATA payload).
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = f => JSON.parse(readFileSync(join(root, 'data', f), 'utf8'));

const base = read('tasks_base.json');
const prices = { tasks: readdirSync(join(root, 'data', 'partials'))
  .filter(f => f.endsWith('.json'))
  .flatMap(f => read(join('partials', f)).tasks) };
const pricing = read('model_pricing.json');
let evidence = { evidence: [], priors_note: '' };
try { evidence = read('reliability_evidence.json'); } catch { /* optional */ }

const priceById = Object.fromEntries(prices.tasks.map(t => [t.task_id, t]));

const tasks = base.tasks.map(t => {
  const p = priceById[t.task_id];
  if (!p) throw new Error(`missing price for ${t.task_id}`);
  return {
    ...t,
    price_low: p.price_low,
    price_base: p.price_base,
    price_high: p.price_high,
    human_minutes: p.human_minutes ?? null,
    price_basis: p.price_basis ?? '',
    price_status: p.status ?? 'estimated',
    sources: p.sources ?? [],
    price_notes: p.notes ?? ''
  };
});

const payload = {
  built: new Date().toISOString().slice(0, 10),
  retrieved: pricing.retrieved,
  models: pricing.models,
  historical: pricing.historical,
  pricing_note: pricing.status_note,
  evidence: evidence.evidence ?? [],
  evidence_note: evidence.priors_note ?? '',
  tasks
};

writeFileSync(join(root, 'site', 'data.js'),
  '// Generated by scripts/build_data.mjs. Do not edit by hand.\n' +
  'window.AEVF_DATA = ' + JSON.stringify(payload, null, 1) + ';\n');

// Compact corpus for the Ask-the-index endpoint (api/chat.js).
const corpus = {
  built: payload.built,
  pricing_note: payload.pricing_note,
  models: pricing.models.map(m => ({ id: m.id, name: m.name, provider: m.provider, input_per_mtok: m.input_per_mtok, output_per_mtok: m.output_per_mtok, cache_read_per_mtok: m.cache_read_per_mtok, tier: m.tier })),
  historical_prices: pricing.historical.map(h => ({ model: h.model, date: h.date, input_per_mtok: h.input_per_mtok, output_per_mtok: h.output_per_mtok })),
  reliability_evidence: (evidence.evidence ?? []).map(e => ({ domain: e.domain, metric: e.metric, value: e.value, measures: e.measures, caveat: e.caveat, source: e.source?.title })),
  reliability_note: evidence.priors_note ?? '',
  review_rates_hr: base.defaults.review_rates_hr,
  tasks: tasks.map(t => ({
    id: t.task_id, name: t.name, domain: t.domain, unit: t.unit, output: t.economic_output,
    price_low: t.price_low, price_base: t.price_base, price_high: t.price_high,
    price_basis: t.price_basis, price_status: t.price_status, human_minutes: t.human_minutes,
    r_low: t.r_low, r_base: t.r_base, r_high: t.r_high, min_reliability: t.min_reliability,
    input_tokens: t.input_tokens, output_tokens: t.output_tokens, attempts_avg: t.attempts_avg,
    tool_cost: t.tool_cost, review_minutes: t.review_minutes, review_role: t.review_role,
    risk_cost: t.risk_cost, risk_class: t.risk_class, verification: t.verification,
    autonomy: t.autonomy, substitutability: t.substitutability, confidence: t.confidence,
    notes: (t.notes + ' ' + (t.price_notes || '')).trim(),
    sources: (t.sources || []).map(s => `${s.publisher || ''}: ${s.title}`)
  }))
};
writeFileSync(join(root, 'api', '_corpus.js'),
  '// Generated by scripts/build_data.mjs. Do not edit by hand.\n' +
  'export const CORPUS = ' + JSON.stringify(JSON.stringify(corpus)) + ';\n');

console.log(`built site/data.js and api/_corpus.js: ${tasks.length} tasks, ${pricing.models.length} models, ${payload.evidence.length} evidence rows`);
