// Merges data/tasks_base.json + data/prices.json + data/model_pricing.json
// + data/reliability_evidence.json into site/data.js (a window.AEVF_DATA payload).
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = f => JSON.parse(readFileSync(join(root, 'data', f), 'utf8'));

const base = read('tasks_base.json');
const prices = { tasks: readdirSync(join(root, 'data', 'partials'))
  .filter(f => f.endsWith('.json'))
  .flatMap(f => read(join('partials', f)).tasks) };
const pricing = read('model_pricing.json');
let evidence = { evidence: [], priors_note: '' };
try { evidence = read('reliability_evidence.json'); } catch { /* optional */ }

const priceById = Object.fromEntries(prices.tasks.map(t => [t.task_id, t]));

const tasks = base.tasks.map(t => {
  const p = priceById[t.task_id];
  if (!p) throw new Error(`missing price for ${t.task_id}`);
  return {
    ...t,
    price_low: p.price_low,
    price_base: p.price_base,
    price_high: p.price_high,
    human_minutes: p.human_minutes ?? null,
    price_basis: p.price_basis ?? '',
    price_status: p.status ?? 'estimated',
    sources: p.sources ?? [],
    price_notes: p.notes ?? ''
  };
});

const payload = {
  built: new Date().toISOString().slice(0, 10),
  retrieved: pricing.retrieved,
  models: pricing.models,
  historical: pricing.historical,
  pricing_note: pricing.status_note,
  evidence: evidence.evidence ?? [],
  evidence_note: evidence.priors_note ?? '',
  tasks
};

writeFileSync(join(root, 'site', 'data.js'),
  '// Generated by scripts/build_data.mjs. Do not edit by hand.\n' +
  'window.AEVF_DATA = ' + JSON.stringify(payload, null, 1) + ';\n');

// Compact corpus for the Ask-the-index endpoint (api/chat.js).
// Kept tight so the system prompt stays under free-tier OpenRouter prompt limits;
// field guide (see api/chat.js system prompt): p = [price_low, base, high] USD;
// r = [r_low, base, high]; fl = min reliability floor; tok = [input, output] per
// attempt; att = retry multiplier; tool/risk = USD per attempt; rev = [minutes, role];
// a/s = autonomy/substitutability 0-5; cf = confidence grade; src = source names.
const trunc = (s, n) => (s || '').length > n ? s.slice(0, n - 1) + '…' : (s || '');
// Base-case metrics precomputed at Claude Sonnet 5 pricing, 50% cache hit, base R
// and base price, so the chat analyst reads instead of re-deriving 50 cost chains.
const SONNET = pricing.models.find(m => m.id === 'claude-sonnet-5');
const RATES = base.defaults.review_rates_hr;
function baseMetrics(t) {
  const cInf = t.attempts_avg * ((t.input_tokens / 1e6) * (0.5 * SONNET.input_per_mtok + 0.5 * SONNET.cache_read_per_mtok) + (t.output_tokens / 1e6) * SONNET.output_per_mtok);
  const cHuman = (t.review_minutes / 60) * (RATES[t.review_role] || 85);
  const cTotal = (cInf + t.tool_cost + cHuman) * 1.1 + t.risk_cost;
  return {
    C: +cTotal.toFixed(2),
    tcevo: +(cInf / t.r_base).toFixed(2),
    fcso: +(cTotal / t.r_base).toFixed(2),
    phi: +((t.r_base * t.price_base) / cTotal).toFixed(1),
    ccr: +(t.price_base / cTotal).toFixed(1)
  };
}
const corpus = {
  built: payload.built,
  models: pricing.models.map(m => ({ id: m.id, name: m.name, in: m.input_per_mtok, out: m.output_per_mtok, cache: m.cache_read_per_mtok })),
  historical_prices: pricing.historical.map(h => `${h.model} (${h.date}): $${h.input_per_mtok}/$${h.output_per_mtok} per Mtok`),
  reliability_evidence: (evidence.evidence ?? []).map(e => `${e.domain} · ${trunc(e.metric, 120)} · ${trunc(e.value, 220)} · measures: ${trunc(e.measures, 150)} · caveat: ${trunc(e.caveat, 120)} (${trunc(e.source?.title, 60)})`),
  reliability_note: trunc(evidence.priors_note ?? '', 900),
  review_rates_hr: base.defaults.review_rates_hr,
  tasks: tasks.map(t => ({
    id: t.task_id, name: t.name, dom: t.domain, unit: t.unit,
    p: [t.price_low, t.price_base, t.price_high],
    r: [t.r_low, t.r_base, t.r_high], fl: t.min_reliability,
    tok: [t.input_tokens, t.output_tokens], att: t.attempts_avg,
    tool: t.tool_cost, rev: [t.review_minutes, t.review_role], risk: t.risk_cost,
    a: t.autonomy, s: t.substitutability, cf: t.confidence,
    m: baseMetrics(t),
    risk_class: t.risk_class, verification: t.verification, human_minutes: t.human_minutes,
    basis: trunc(t.price_basis, 140), note: trunc((t.notes + ' ' + (t.price_notes || '')).trim(), 220),
    src: (t.sources || []).slice(0, 3).map(s => trunc(`${s.publisher || ''}: ${s.title}`, 70))
  }))
};
writeFileSync(join(root, 'api', '_corpus.js'),
  '// Generated by scripts/build_data.mjs. Do not edit by hand.\n' +
  'export const CORPUS = ' + JSON.stringify(JSON.stringify(corpus)) + ';\n');

console.log(`built site/data.js and api/_corpus.js: ${tasks.length} tasks, ${pricing.models.length} models, ${payload.evidence.length} evidence rows`);
